package rit.eyeTrackingAPI;

/**
 * Implemented by objects that want to be notified of eye tracking
 * events, be they generated by an eye tracking device or by replay
 * from a file.
 * 
 * @see Source
 * @see rit/eyeTrackingAPI/EyeTrackerUtilities/udpClients/EyeTrackerClient
 */
public interface EyeTrackingListener {
	
	/**
	 * Notifies the listener of the given eye tracking event.
	 * 
	 * The attributes of the event should be read before the
	 * notify method returns, for the event will be destroyed
	 * after the last listener has been notified.
	 * 
	 * @param e The eye tracking event
	 */
	public void notify(Event e, EyeTrackingListener listener);
}
